"""Initial core models

Revision ID: 1fda9bb174db
Revises:
Create Date: 2026-04-07 22:07:50.779465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fda9bb174db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('capability_key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('safety_level', sa.String(), nullable=True),
    sa.Column('parameter_schema_json', sa.JSON(), nullable=True),
    sa.Column('ui_hints_json', sa.JSON(), nullable=True),
    sa.Column('voice_examples_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_capability_key'), 'capabilities', ['capability_key'], unique=True)
    op.create_table('command_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('source_interface', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('turn_id', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('capability_id', sa.String(), nullable=False),
    sa.Column('adapter_id', sa.String(), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_executions_correlation_id'), 'command_executions', ['correlation_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('transcript_raw', sa.String(), nullable=True),
    sa.Column('transcript_normalized', sa.String(), nullable=True),
    sa.Column('parsed_intent_json', sa.JSON(), nullable=True),
    sa.Column('clarification_required', sa.Boolean(), nullable=False),
    sa.Column('executed_plan_json', sa.JSON(), nullable=True),
    sa.Column('response_text', sa.String(), nullable=True),
    sa.Column('tts_run_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_session_id'), 'conversation_turns', ['session_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=True),
    sa.Column('friendly_name', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('auth_ref_id', sa.String(), nullable=True),
    sa.Column('adapter_id', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health_state', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    op.drop_index(op.f('ix_conversation_turns_session_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_command_executions_correlation_id'), table_name='command_executions')
    op.drop_table('command_executions')
    op.drop_index(op.f('ix_capabilities_capability_key'), table_name='capabilities')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
